### ISSUE TITLE
Multiple breadcrumbs should be displayed more compactly

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#276]
* https://www.clas-digital.uni-frankfurt.de/books/CZTTE7FV/

has six breadcrumb navigation lines.  These could be displayed more compactly by removing additional padding/border/spacing;  the source of this extra space is a combination of:

```css
nav ol.breadcrumb {
  padding-top: 12;
  padding-bottom: 12;
  margin-bottom: 12;
}
nav ol.breadcrumb li.breadcrumb-item {
  margin-top: 16;
  margin-bottom: 16;
}
```
